name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Specify the .NET version to use

      - name: Restore NuGet packages
        run: dotnet restore ExpansionExplorer.sln

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2 # Set up MSBuild for building .NET projects

      - name: Build solution
        run: msbuild ExpansionExplorer.sln /p:Configuration=Release

      - name: Publish GUIExplorer.WPF
        run: dotnet publish GUIExplorer.WPF/GUIExplorer.WPF.csproj -c Release -r win-x64 --self-contained false -o publish

      # Create a ZIP file of the published output
      - name: Create release ZIP
        run: Compress-Archive -Path publish\* -DestinationPath GUIExplorer.WPF.zip

      # Upload the ZIP file to the GitHub release
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: GUIExplorer.WPF.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}